# Generated by Django 3.0.7 on 2020-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Album name')),
                ('aid', models.IntegerField(max_length=16, verbose_name='Album id')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Playlist name')),
                ('pid', models.IntegerField(max_length=16, verbose_name='Playlist id')),
                ('type', models.IntegerField(max_length=1, verbose_name='Playlist type')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Song name')),
                ('sid', models.IntegerField(max_length=16, verbose_name='Song id')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='User name')),
                ('uid', models.IntegerField(max_length=16, verbose_name='User id')),
                ('playlist', models.ManyToManyField(to='netease_api.PlayList', verbose_name='User playlists')),
                ('song', models.ManyToManyField(to='netease_api.Song', verbose_name='User songs')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='netease_api.Song', verbose_name='Playlist songs'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Artist name')),
                ('aid', models.IntegerField(max_length=16, verbose_name='Artist id')),
                ('album', models.ManyToManyField(to='netease_api.Album', verbose_name='Artist albums')),
                ('song', models.ManyToManyField(to='netease_api.Song', verbose_name='Artist songs')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(to='netease_api.Song', verbose_name='Album songs'),
        ),
    ]
