# Generated by Django 3.0.7 on 2020-06-24 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
        migrations.RemoveField(
            model_name='user',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='imgUrl',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='封面Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='简介'),
        ),
    ]
