# Generated by Django 3.0.7 on 2020-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0002_添加imgUrl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Album id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Artist id'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='歌单ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Song id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='User id'),
        ),
    ]
