# Generated by Django 3.0.7 on 2020-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0003_把aid_pid_sid等改成id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='master_user',
        ),
        migrations.AddField(
            model_name='playlist',
            name='master_uid',
            field=models.IntegerField(default=None, verbose_name='创建该歌单的用户'),
            preserve_default=False,
        ),
    ]
