# Generated by Django 3.0.7 on 2020-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0005_删除模型PlayList的ordered字段'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='', max_length=100, verbose_name='头像地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='background_url',
            field=models.CharField(default='', max_length=100, verbose_name='背景图片地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=None, verbose_name='生日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.IntegerField(default=100, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(default=None, verbose_name='注册时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='master_uid',
            field=models.IntegerField(verbose_name='创建该歌单的用户的id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(to='netease_api.PlayList', verbose_name='用户拥有的歌单'),
        ),
    ]
