# Generated by Django 3.0.7 on 2020-06-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0006_完善User模型'),
    ]

    operations = [
        migrations.CreateModel(
            name='alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='别名')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='desc',
            field=models.CharField(default='', max_length=1000, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='artist',
            name='imgUrl',
            field=models.CharField(default='', max_length=100, verbose_name='头像地址'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user_id',
            field=models.IntegerField(default=None, verbose_name='对应用户的id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='album',
            field=models.ManyToManyField(to='netease_api.Album', verbose_name='歌手拥有的专辑'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='歌手id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=30, verbose_name='歌手名'),
        ),
        migrations.AddField(
            model_name='artist',
            name='alias',
            field=models.ManyToManyField(to='netease_api.alias', verbose_name='歌手的其他名称'),
        ),
    ]
