# Generated by Django 3.0.7 on 2020-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0007_完善Artist模型_新建alias和tag模型'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='发行商'),
        ),
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='album',
            name='imgUrl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='subtype',
            field=models.CharField(default='录音室版', max_length=50, verbose_name='子类型'),
        ),
        migrations.AddField(
            model_name='album',
            name='tag',
            field=models.ManyToManyField(to='netease_api.tag', verbose_name='专辑标签'),
        ),
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(default='专辑', max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='专辑id'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='专辑名'),
        ),
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(to='netease_api.Song', verbose_name='专辑包涵的单曲'),
        ),
    ]
