# Generated by Django 3.0.7 on 2020-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0009_完善Song模型'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='对应用户的id'),
        ),
    ]
