# Generated by Django 3.0.8 on 2020-07-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netease_api', '0010_为模型Artist的user_id字段添加默认值0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tag',
            field=models.ManyToManyField(to='netease_api.Tag', verbose_name='专辑标签'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='alias',
            field=models.ManyToManyField(to='netease_api.Alias', verbose_name='歌手的其他名称'),
        ),
    ]
